# Blowfish Menu Configuration

[[main]]
  name = "Texts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/tiagovignatti"
  weight = 40

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/tiagovignatti"
  weight = 50
