# Blowfish Theme Parameters

description = "Exploring software, media, and social systems as paths to empower nature."

colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = false

Logo = "images/avatar.png"
disableTextInHeader = true

enableSearch = false
enableCodeCopy = true
highlightCurrentMenuArea = true

[footer]
  showAppearanceSwitcher = false

mainSections = ["posts"]

[homepage]
  layout = "custom"
  homepageImage = ""
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  showTaxonomies = false
  showWordCount = false
  sharingLinks = ["email"]

[list]
  showHero = false
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false
  showTaxonomies = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  # Your Firebase config here if needed

[fathomAnalytics]
  # site = "ABC12345"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
